blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_posts, name="posts"),
    path("<int:post_id>", post_detail, name="post_detail"),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("blog", include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/image")
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/image/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, "posts.html", {"posts": posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

portfolio/views.py
from django.shortcuts import render

from .models import Project


def home(request):
    projects =  Project.objects.all()
    return render(request, 'home.html', {"projects": projects})

blog/templates/post_detail.html
{% extends 'layout.html' %} {% block content %}
<div class="text-center">
  <h2>{{ post.title }}</h2>
  <h3 class="my-2 h5 text-muted">{{ post.date }}</h3>
  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" />
  <div class="my-4">
    <p>{{ post.description|safe }}</p>
  </div>
</div>
{% endblock content %}

blog/templates/posts.html
{% extends 'layout.html' %} {% block content %} {% for post in posts %}
<div class="p-3">
  <div class="card card-body bg-black">
    <div class="row">
      <div class="col-3">
        <img
          src="{{ post.image.url }}"
          alt="{{ post.title }}"
          class="img-fluid"
        />
      </div>
      <div class="col-9">
        <h2>{{ post.title }}</h2>
        <h3>{{ post.date|date:'M j Y'|upper }}</h3>
        <p>{{ post.description|striptags|truncatechars:100 }}</p>
        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-outline-primary">{{ post.title }}</a>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock content %}

portfolio/templates/home.html
{% extends 'layout.html' %} {% block content %} {% load static %}
<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'portfolio/foto.jpg' %}" alt="" class="img-fluid" />
  </div>
  <div class="col-md-8 my-auto">
    <h1>Sebastian Rodriguez</h1>
    <h3>Soy un Python Fullstack Developer</h3>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum
      necessitatibus blanditiis voluptates dolores, quasi corporis ex eum
      reprehenderit dolor quos, mollitia consectetur et, recusandae sequi
      facere. Tempora repellat fuga quas natus ut vel numquam ad. Tempora, omnis
      odit! Veniam, quia officia asperiores dolorem sunt aliquid ullam totam
      quidem quasi saepe. Sapiente quos quibusdam laborum iste dolorem
      laudantium autem distinctio eveniet consequatur aspernatur adipisci minus
      velit dicta ut possimus, reprehenderit cumque nisi placeat minima labore,
      vitae magni. Incidunt, suscipit nihil quasi facere corrupti fugit ad
      laudantium temporibus commodi vero repellat vel consequatur facilis,
      asperiores eveniet nisi tempore, perspiciatis maxime excepturi? Nobis?
    </p>
    <a
      href="{% static 'portfolio/Profile.pdf' %}"
      class="btn btn-outline-primary btn-lg rounded-0 my-3"
      target="_blank"
      >Download CV</a
    >
  </div>
</header>
<h3>Mis Proyectos</h3>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vel, nisi?</p>
<div class="row my-4 text-center">
  {% for project in projects %}

  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img
        src="{{ project.image.url }}"
        alt="{{ project.title }}"
        class="img-fluid"
      />
      <div class="card-body">
        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>
        {% if project.url %}
        <a
          href="{{ project.url }}"
          class="btn btn-outline-light rounded-0 btn-sm mx-auto"
          >{{ project.url|truncatechars:15 }}</a
        >
        {% endif %}
      </div>
    </div>
  </div>

  {% endfor %}
</div>
{% endblock content %}

portfolio/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Django Portfolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- main.css -->
    <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css">
  </head>
  <body class="text-light">
      
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
    {% block content %}{% endblock %}
    </div>


    <footer>Footer</footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/partials/navbar.html
{% load static%}
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container">
    <a class="nav-link fw-bold fst-italic" href="/"
      >Home <span class="visually-hidden">(current)</span></a
    >
    <ul class="nav navbar-nav ms-auto">
      <div class="collapse navbar-collapse">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-item-center">
          <a
            class="btn btn-outline-primary btn-sm"
            href="{% static 'portfolio/Profile.pdf' %}"
            target="_blank"
            role="button"
            >Download CV</a
          >
        </li>
      </div>
    </ul>
  </div>
</nav>